version: '3'

services:
    nginx:
        image: nginx:latest
        environment:
            - TZ=Asia/Shanghai
        # 端口映射
        ports:
            - "80:80"
            - "443:443"
        # 数据卷
        volumes:
            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
            - "$PWD/nginx/conf.d:/etc/nginx/conf.d"
            - "$PWD/nginx/project:/var/www/html"
            - "/home/cvl/nginx/nginx/cert/www.hi5fun.net_nginx:/root/www.hi5fun.net_nginx"
        # 容器名称
        container_name: "compose-nginx"